spring:
  application:
    name: MITOCODE
  datasource:
    url: jdbc:postgresql://localhost/mediapp_2024
    username: postgres
    password: MyS3cretPa55
    hikari:
      driver-class-name: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      platform: org.hibernet.dialect.PostgresSQLDialect

