package com.mitocode.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwt;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import jakarta.websocket.OnClose;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * This class is to build or generate a JWT
 */
@Component
public class JwtTokenUtil implements Serializable {
    private final long JWT_TOKEN_VALIDITY = 5*60*60*1000; // 5 Horas
    @Value("${jwt.secret}") // ${} El Expression Language
    private String secret;

    /**
     * This method make the JWt
     * @param userDetails is the User's data like name and password
     * @return a new JWT with some payload generated by the user's data
     */
    public String generateToken(UserDetails userDetails){
        Map<String, Object> claims = new HashMap<>();
        claims.put("role", userDetails.getAuthorities().stream().map(GrantedAuthority::getAuthority).collect(Collectors.joining(",")));
        claims.put("test","JulioTests");

        return doGenerateToken(claims, userDetails.getUsername());
    }

    /**
     * This method build the JWT
     * @param claims is the payload that'll contain the token
     * @param username  is the user's name
     * @return the Token JWT built
     */
    private String doGenerateToken(Map<String, Object> claims, String username){

        SecretKey key = Keys.hmacShaKeyFor(this.secret.getBytes());

        return Jwts.builder()
                .claims(claims)
                .subject(username)
                .issuedAt(new Date(System.currentTimeMillis()))
                .expiration(new Date(System.currentTimeMillis() + JWT_TOKEN_VALIDITY))
                .signWith(key)
                .compact();
    }

    public Claims getAllClaimsToken(String token){
        SecretKey key = Keys.hmacShaKeyFor(this.secret.getBytes());
        return Jwts.parser().verifyWith(key).build().parseSignedClaims(token).getPayload();
    }

    /**
     * This is a method generic that return a data from a jwt
     * @param token is the JWT
     * @param claimResolver is an expression lamda or function
     * @return some JWT's attribute
     * @param <T> this is the generic type
     */
    public <T> T getClaimFromToken(String token, Function<Claims, T> claimResolver){
        final Claims claim = getAllClaimsToken(token);
        return claimResolver.apply(claim);
    }

    public String getUserNameFromToken(String token){
        return getClaimFromToken(token, Claims::getSubject);
    }

    public Date getDateExpirationFromToken(String token){
        return getClaimFromToken(token, Claims::getExpiration);
    }

    public boolean isTokenExpired(String token){
        final Date expiration = getDateExpirationFromToken(token);
        return expiration.before(new Date());
    }

    public boolean validaToken(String token, UserDetails userDetails){
        final String username = getUserNameFromToken(token);
        return (username.equalsIgnoreCase(userDetails.getUsername()) && !isTokenExpired(token));
    }

}
